### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by MyDigitalLife** [brexis/laravel-workflow#16]
So its been almost a months after I made my first pull request and have not gotten any response back yet. If this repo is no longer being maintained can we mark it as that? If its not abandoned can we maybe add someone with more time so that we have somebody that can review, merge and release other then @brexis?

**Comment by willemo** [comment]
You could fork this project and work on that. I'd have some potential PRs to contribute.

**Comment by MyDigitalLife** [comment]
Yeah i'm most likely going to do that somewhere this weekend.

**Comment by brexis** [comment]
Abandoned... Absolutely not? Hi guys,
First of all thanks for your interest in this project. My apologies for my silence, I was a bit busy with side projects. I'll check your contributions and let you know.
