### ISSUE TITLE
Workflow <my_workflow> has no support for class 

### ISSUE THREAD

**Issue by agamayaservers** [brexis/laravel-workflow#20]
when I try to dump a workflow by:
php artisan dump:workflow my_workflow
I get an error like this:
In WorkflowDumpCommand.php line 53:
  Workflow <my_workflow> has no support for class 

in config there is a row with "supports" parameter and correct value (because workflow is working)
how to solve it?

**Comment by brexis** [comment]
Hey, @agamayaservers  can you paste her your `config/workflow.php` file content?

**Comment by faycal1** [comment]
HI , First of All Congrat For the Library Very Usefull,

Is There A way To Use
 workflow_can()
workflow_transitions()
workflow_marked_places()
workflow_has_marked_place()

in blade template ?

Like in the example of Symfony https://symfony.com/doc/current/workflow/usage.html

Thank's

**Comment by brexis** [comment]
Hi @faycal1, it's not possible yet. I will probably work on it this weekend.

**Comment by faycal1** [comment]
Thank you for the quick Answer @brexis , i did manage to make it work by adding a helper function 
function workflow_can( $model , $workflow , $place ) and it work correctly , but wonder if there is not an elegant way to accomplish that, thank you

**Comment by Olarewaju** [comment]
Hi, @faycal1 having the same issue, kindly how you fixed it. Thanks.

**Comment by faycal1** [comment]
Hi ,

In helpers.php

add This Function

`if (! function_exists('workflow_can')) {

    /**
     * @return boolean
     */
    function workflow_can( $model, $workflow , $place )
    {
        $workflow = \Workflow::get($model, $workflow) ;

        if($workflow->can($model, $place)) {
            return true ;
        }       

        return false ;
    }
}`

in the view , call the function
`
@if(workflow_can($post, 'straight' ,'publish'))
       <a href="...">Publish article</a>
@endif
`

hope it help

**Comment by iamNikitaValty** [comment]
Hi, I'm having this same issue and do not know how to make it work. @brexis  is there any answer yet ?

My config/workflow.php looks like this

<?php

return [
    'straight'   => [
        'type'          => 'state_machine',
        'marking_store' => [
            'type' => 'multiple_state',
        ],
        'supports'      => ['App\Models\Folder'],
        'places'        => ['new', 'prepreselected','completed','preselected','training','selected','finish'],
        'transitions'   => [
            'prepreselection' => [
                'from' => 'new',
                'to'   => 'prepreselected',
            ],
            'folder_completion' => [
                'from' => 'prepreselected',
                'to'   => 'completed',
            ],
            'preselection' => [
                'from' => 'completed',
                'to'   => 'preselected',
            ],
            'forced_preselection' => [
                'from' => 'prepreselected',
                'to'   => 'preselected',
            ],
            'training' => [
                'from' => 'preselected',
                'to'   => 'training',
            ],
            'selection' => [
                'from' => 'training',
                'to'   => 'selected',
            ],
            'confirmation' => [
                'from' => 'selected',
                'to'   => 'finish',
            ]
        ],
    ]
];

I even tried with
 'supports'      => [App\Models\Folder::class],  and  'supports'      => [Folder::class], but i keep having the issue

**Comment by brexis** [comment]
Hi @iamNikitaValty  what is your laravel version?

**Comment by iamNikitaValty** [comment]
I'm using Laravel 5.5 sorry

2018-03-12 22:25 GMT+01:00 Boris KOUMONDJI <notifications@github.com>:

**Comment by begnini** [comment]
I'm having the same problem. When debugging, var_dumping the variable $class from

`$class          = $this->option('class');`

is printing null. To make it work, I have to pass the class name with the option --class. Example:

`php artisan workflow:dump article --format=jpg --class App\Article`

**Comment by swatkins** [comment]
I'm running Laravel 5.6 and running `php artisan workflow:dump requestWorkflow --format=jpg --class App/Models/Project`. I get this error:

```
Workflow requestWorkflow has no support for class App/Models/Project 
```

Please help.

**Comment by lguima** [comment]
On **Laravel 5.5** I'm usign the command like this and it's working:

`php artisan workflow:dump workflow_name --class=App\\Class`

**Comment by brexis** [comment]
I guess the documentation must mention how to use support class option.

**Comment by brexis** [comment]
Closing this as it has been documented.
