### ISSUE TITLE
Listen to specific events

### ISSUE THREAD

**Issue by lguima** [brexis/laravel-workflow#25]
How can I use events like described on [Symfony Workflow](http://symfony.com/doc/current/workflow/usage.html#using-events) component?

`workflow.guard`
`workflow.[workflow name].guard`
`workflow.[workflow name].guard.[transition name]`

**Comment by brexis** [comment]
This has been added since [1.2.0](https://github.com/brexis/laravel-workflow/blob/master/src/Events/WorkflowSubscriber.php#L14). You can subscribe to guard events like symfony workflow does.
