### ISSUE TITLE
config path issue

### ISSUE THREAD

**Issue by YuviPO** [brexis/laravel-workflow#27]
Hi,

I'm using lumen 5.6.

I did the steps ::
1. composer require : "brexis/laravel-workflow": "^1.2"
2. bootstrap/app.php : 
    I. $app->register(Brexis\LaravelWorkflow\WorkflowServiceProvider::class);
    II. $app->routeMiddleware(['Workflow' => Brexis\LaravelWorkflow\Facades\WorkflowFacade::class,]);

And i publish the vendor using this command

php artisan vendor:publish --provider="Brexis\LaravelWorkflow\WorkflowServiceProvider"

I got a error:

In WorkflowServiceProvider.php line 25:

  Call to undefined function Brexis\LaravelWorkflow\config_path()

Kindly clear this issue.

Thanks.

**Comment by brexis** [comment]
This package is not compatible with Lumen.
