### ISSUE TITLE
Symfony 4.1 metadata is not accessible

### ISSUE THREAD

**Issue by WulfP** [brexis/laravel-workflow#28]
even after changes from [New in Symfony 4.1: Workflow improvements](https://symfony.com/blog/new-in-symfony-4-1-workflow-improvements) were applied:

WorkflowRegistry.php:

use Symfony\Component\Workflow\SupportStrategy\InstanceOfSupportStrategy;
public function add(Workflow $workflow, $supportStrategy)
    {
        $this->registry->addWorkflow($workflow, new InstanceOfSupportStrategy($supportStrategy));
    }

InMemoryMetadataStore {#1152
  -workflowMetadata: []
  -placesMetadata: []
  -transitionsMetadata: SplObjectStorage {#1153
    storage: []
  }
}
metadata ist defined but MetadataStore stays empty.

Sorry. I tried but was not able to fix it.
Maybe some Symfony-Components to handle metadata are missing.

**Comment by brexis** [comment]
Hi @WulfP. We do not support yet Symfony 4.1.

**Comment by MyDigitalLife** [comment]
Seeing that 4.1 is not support the composer.json should be updated to reflect this. This way there is no question if it is supported or not.

**Comment by brexis** [comment]
Fixed in the last release 1.3.0.
