### ISSUE TITLE
Where does the data stored?

### ISSUE THREAD

**Issue by hdrm147** [brexis/laravel-workflow#30]
Where the data stored? DB? Or System Files? Memory?
by data i mean the current place for some model

**Comment by himan72** [comment]
same question for me ????

**Comment by himan72** [comment]
ok i figure out the answer we must add a field type json to the model table (name can be set on the config file under arguments) and cast it to an array

**Comment by error500** [comment]
First you should create a field in Post model, ie Post->status
Then in config, first argument is the name of this field


    'marking_store' => [

        'type'      => 'multiple_state',

        'arguments' => ['status']

    ],

$post->save(); saves the current place in the Post model.

Without name in config, default name is `marking`

**Comment by brexis** [comment]
Closing this as @error500  answer the question.
