### ISSUE TITLE
composer require fail

### ISSUE THREAD

**Issue by hawkefly** [brexis/laravel-workflow#32]
composer require brexis/laravel-workflow
Using version ^1.2 for brexis/laravel-workflow
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 4 installs, 0 updates, 0 removals
  - Installing symfony/inflector (v4.1.2): Loading from cache
  - Installing symfony/property-access (v4.1.2): Loading from cache
  - Installing symfony/workflow (v4.1.2): Loading from cache
  - Installing brexis/laravel-workflow (1.2.1): Loading from cache
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan ide-helper:generate

   Symfony\Component\Debug\Exception\FatalThrowableError  : Argument 1 passed to Brexis\LaravelWorkflow\WorkflowRegistry::__construct() must be of the type array, null given, called in /Users/liwei/PhpstormProjects/eCollect/vendor/brexis/laravel-workflow/src/WorkflowServiceProvider.php on line 39

  at /Users/liwei/PhpstormProjects/eCollect/vendor/brexis/laravel-workflow/src/WorkflowRegistry.php:44

**Comment by brexis** [comment]
Hi @hawkefly 
I just released a new version that should fix this.

**Comment by hawkefly** [comment]
Thank you for your quick response.
