### ISSUE TITLE
Workflow $workflowName is not configured

### ISSUE THREAD

**Issue by zayaslui** [brexis/laravel-workflow#50]
Exception  : Workflow workflow_name is not configured.

  at /var/www/html/laravel/brexis/vendor/symfony-rot-ebal/laravel-workflow/src/Commands/WorkflowDumpCommand.php:49
    45|         $class          = $this->option('class');
    46|         $config         = Config::get('workflow');
    47| 
    48|         if (!isset($config[$workflowName])) {
  > 49|             throw new Exception("Workflow $workflowName is not configured.");
    50|         }
    51| 
    52|         if (false === array_search($class, $config[$workflowName]['supports'])) {
    53|             throw new Exception("Workflow $workflowName has no support for class $class.".

  Exception trace:

  1   Brexis\LaravelWorkflow\Commands\WorkflowDumpCommand::handle()
      /var/www/html/laravel/brexis/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:32

  2   call_user_func_array([])
      /var/www/html/laravel/brexis/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:32

  Please use the argument -v to see more details.

**Comment by zerodahero** [comment]
To dump out the workflow, you'll need to provide both the workflow name and the class, e.g. `php artisan workflow:dump --class='App\BlogPost' straight`

**Comment by zayaslui** [comment]
Thanks.
