### ISSUE TITLE
dot command error on windows

### ISSUE THREAD

**Issue by redmagi** [brexis/laravel-workflow#54]
my project run on windows server. 
it can not used [Dot (command)](https://en.wikipedia.org/wiki/Dot_(command))  by default.
i must install [graphviz](https://graphviz.gitlab.io/_pages/Download/Download_windows.html) 
[Graphviz: How to go from .dot to a graph?](https://stackoverflow.com/questions/1494492/graphviz-how-to-go-from-dot-to-a-graph).
[How to install Graphviz software](https://bobswift.atlassian.net/wiki/spaces/GVIZ/pages/20971549/How+to+install+Graphviz+software)

may you add note in documant of this package

thank you
pitt phunsanit

**Comment by brexis** [comment]
HI @redmagi. There is already a note about Graphviz in the documentation.
