### ISSUE TITLE
Installation request for brexis/laravel-workflow ^1.3 -> Conclusion: remove symfony/console

### ISSUE THREAD

**Issue by cdric0701** [brexis/laravel-workflow#59]
Hello,
I encounter problem when using this package with laravel 5.8.
Here is the message:
![brexis](https://user-images.githubusercontent.com/6715950/63430829-dbaaa480-c41d-11e9-97cd-1d3aaba92912.PNG)

If anyone has a solution ?
Thanks :)

**Comment by brexis** [comment]
Hi @cdric0701 . Version 1.3 does not support symfony 4.3 components. What is your laravel version?

**Comment by cdric0701** [comment]
Hello @brexis I have Laravel 5.8

**Comment by kblais** [comment]
@cdric0701 I opened a PR that should make this work (#58), feel free to test if it works with the modifications I made (use my fork while the PR is not merged)

**Comment by brexis** [comment]
@cdric0701  please try version 1.3.1. Thanks to @kblais.
