### ISSUE TITLE
Drop support for symfony/workflow 3.2?

### ISSUE THREAD

**Issue by laurenkt** [brexis/laravel-workflow#6]
The project's current requirements in `composer.json` allow it to be used with symfony/workflow 3.2. 

However, due to #2, the project will no longer work with 3.2.

It will throw the following error (in `WorkflowRegistry.php` line 63):

```
[Symfony\Component\Debug\Exception\FatalThrowableError]                                    
Class 'Symfony\Component\Workflow\SupportStrategy\ClassInstanceSupportStrategy' not found
```

So a decision needs to be made about whether to patch in support for 3.2 again, or revert the change, or drop support for 3.2 from `composer.json`.

**Comment by brexis** [comment]
Hi @laurenkt. 
I will release a new version (1.1.0) which should support Symfony workflow 3.3 with a support of laravel 5.4 and 5.5. Users can still use the version 1.0 if they want to support Symfony workflow 3.2.

**Comment by brexis** [comment]
Done.
