### ISSUE TITLE
cannnot install in laravel 6

### ISSUE THREAD

**Issue by redmagi** [brexis/laravel-workflow#61]
this package cannot install in laravel 6

**Comment by arjanwestdorp** [comment]
PR #60 will fix this.

**Comment by arjanwestdorp** [comment]
@brexis Can you please tag a new version? The 1.3.2 version seems to be created BEFORE #60 was merged.

It's still not possible to install with Laravel 6 as 1.3.2 doesn't have the updated composer.json file.

**Comment by brexis** [comment]
@arjanwestdorp Sorry about that. Can you try the version 1.3.3 and let me know.

**Comment by arjanwestdorp** [comment]
Works fine now. Thanks!
