### ISSUE TITLE
Unable to find a workflow for class "App\BlogPost"

### ISSUE THREAD

**Issue by pgiannitsaros** [brexis/laravel-workflow#67]
I followed all instructions, using laravel 6.6.2 and exection occurs `Unable to find a workflow for class "App\BlogPost". `. 
![laravel](https://user-images.githubusercontent.com/46202117/70277924-f4b44700-17bb-11ea-9dc2-3e7968224e8f.png)

 I also want to mension that I couldn' find any database schema for blog_posts. 
Would you like to give a link about it for more details?

**Comment by brexis** [comment]
@gpanagiotis  The `supports` attribute must contain the models which you are defining the workflow for. I can be any model in your application.
