### ISSUE TITLE
Simple Sample please

### ISSUE THREAD

**Issue by jfpwork** [brexis/laravel-workflow#9]

**Comment by brexis** [comment]
Hi @jfpwork, did you try this https://github.com/brexis/laravel-workflow#usage ?

**Comment by jfpwork** [comment]
Yep but Namespace missing ... 
So I try another workflow (https://gist.github.com/iben12/7e24b695421d92cbe1fec3eb5f32fc94)
Step By Step Implementation could help many futur users
or probably a simple Controller to demonstrate "How to use it"

**Comment by brexis** [comment]
I think you may forget the Workflow alias configuration in your Laravel project. https://github.com/brexis/laravel-workflow#installation

**Comment by jfpwork** [comment]
First thanks. 
In fact i follow your steps : 
[OK] Installtion : composer, add provider and facade
[OK] Configuration:  publish and add the trait to the Model.
Then i would like to test your workflow in a controller who manage a Model with your trait.
So 

<?php
namespace App\Http\Controllers;
use App\BlogPost;
/* here missing the path to Workflow */
class BlogPostController extends Controller{
    public function test()
    {
       $post = BlogPost::find(1);
       $workflow = Workflow::get($post); <--- exception
    }

I will retry today to implement your package
Have a good day

**Comment by boneq** [comment]
@jfpwork My problem is the same as yours.

**Comment by MyDigitalLife** [comment]
You can fix this by using mutators: https://laravel.com/docs/5.5/eloquent-mutators
So my model would look like this:
```
class BlogPost extends Model
{
    use WorkflowTrait;

    public function setCurrentPlaceAttribute($value)
    {
        $this->attributes['currentPlace'] = json_encode($value);
    }

    public function getCurrentPlaceAttribute()
    {
        return json_decode($this->attributes['currentPlace'], true);
    }
}
```

**Comment by brexis** [comment]
I'm closing this issue as it's not related to laravel-workflow but to laravel.

**Comment by qerim** [comment]
> You can fix this by using mutators: https://laravel.com/docs/5.5/eloquent-mutators
> So my model would look like this:
> 
> ```
> class BlogPost extends Model
> {
>     use WorkflowTrait;
> 
>     public function setCurrentPlaceAttribute($value)
>     {
>         $this->attributes['currentPlace'] = json_encode($value);
>     }
> 
>     public function getCurrentPlaceAttribute()
>     {
>         return json_decode($this->attributes['currentPlace'], true);
>     }
> }
> ```

Or you could simply write it as:

```
class BlogPost extends Model
{
    use WorkflowTrait;

    protected $casts = [
        'currentPlace' => 'json'
    ];
}
```
